'use strict';
window.LearnLesson=(()=>{
 let A,session=null,step=0,answered=false,assisted=false,bank=[],picked=[],revealed=false,traceWord=null,exitPending=false,answerLog=[],exposed=new Set(),resumeMarkup='',resumeInput='';
 const $=s=>document.querySelector(s),dialog=()=>$('#lesson'),root=()=>$('#lesson-content');
 const current=()=>session?.steps[step],w=()=>current()?.word;
 const button=(label,action,cls='primary-btn',extra='')=>`<button class="${cls}" data-lesson="${action}" ${extra}>${label}</button>`;
 function init(api){A=api;root().addEventListener('click',e=>{const b=e.target.closest('[data-lesson]');if(!b||b.disabled)return;act(b.dataset.lesson,b);});root().addEventListener('submit',e=>{if(e.target.id==='writing-form'){e.preventDefault();checkWriting();}});dialog().addEventListener('cancel',e=>{e.preventDefault();requestExit();});dialog().addEventListener('close',()=>A.Audio.stop());}
 function start({mode,words}){
  A.Audio.stop();traceWord=null;answerLog=[];exposed=new Set();step=0;exitPending=false;const practiceMode=A.profile().settings.mode;
  const steps=[];
  if(mode==='lesson')steps.push(...words.map(word=>({type:'learn',word})));
  steps.push(...A.C.shuffle(words).map(word=>({type:'listen',word})));
  if(!['weekly','practice'].includes(mode)&&practiceMode!=='listen')steps.push(...A.C.shuffle(words).map(word=>({type:practiceMode,word})));
  session={id:A.C.uid(),mode,words,steps,options:[]};dialog().showModal();draw();
 }
 function top(){return`<div class="lesson-top">${button(A.icon('close'),'exit','icon-btn','aria-label="Salir de la actividad"')}<div class="lesson-progress" role="progressbar" aria-label="Progreso de la actividad" aria-valuemin="0" aria-valuemax="${session.steps.length}" aria-valuenow="${step}"><i style="width:${step/session.steps.length*100}%"></i></div><span class="lesson-counter">${step+1} / ${session.steps.length}</span>${button(A.icon('sound'),'instruction','icon-btn','aria-label="Escuchar instrucciones"')}</div>`;}
 function footer(label='Continuar',action='next',disabled=false){const p=A.profile();return`<footer class="lesson-footer"><div class="companion-hint"><span class="mini-mascot ${p.companion}"><img src="assets/milo-lumi.webp" alt="" width="1100" height="733"></span><span>${p.companion==='lumi'?'Lumi':'Milo'} está contigo.<br>Vamos a tu ritmo.</span></div>${button(label+' '+A.icon('arrow'),action,'primary-btn',disabled?'disabled':'')}</footer>`;}
 function audioButtons(word){return`<div class="audio-actions">${button(A.icon('sound')+' Escuchar','audio','',`data-id="${word.id}"`)}${button(A.icon('clock')+' Más lento','slow','',`data-id="${word.id}"`)}</div>`;}
 function draw(){
  A.Audio.stop();answered=false;assisted=false;revealed=false;picked=[];exitPending=false;const part=current(),word=part.word,cat=A.category(word.category);bank=A.C.shuffle([...word.en].map((letter,i)=>({letter,id:i})));
  let body,foot;
  if(part.type==='learn'){
   exposed.add(word.id);body=`<div class="lesson-body"><span class="section-eyebrow">VAMOS A DESCUBRIR · ${cat.es}</span><h2 id="lesson-title">Mira. Escucha. ¡Hola, palabra!</h2><p class="lesson-sub">Puedes escucharla tantas veces como quieras.</p><div class="lesson-flash"><div class="art-stage" style="--world:${cat.color}">${A.image(word,'',word.es)}</div><div><h3 lang="en">${word.en}</h3>${A.profile().settings.translation?`<p>${word.es}</p>`:'<p></p>'}${audioButtons(word)}<button class="sentence-button" data-lesson="audio" data-id="${word.id}-sentence">${A.icon('sound')}<span lang="en">${word.sentence}</span></button></div></div></div>`;foot=footer('Ya la descubrí');
  }else if(part.type==='listen'){
   const others=A.C.shuffle(A.catalog.words.filter(q=>q.category===word.category&&q.id!==word.id)).slice(0,2);session.options=A.C.shuffle([word,...others]);
   body=`<div class="lesson-body"><span class="section-eyebrow">${['weekly','practice'].includes(session.mode)?'RETO DE PALABRAS':'ESCUCHA Y DESCUBRE'}</span><h2 id="lesson-title">¿Cuál escuchaste?</h2><p class="lesson-sub">Toca el altavoz. Después, elige una imagen.</p>${button(A.icon('sound')+' Escuchar palabra','audio','big-audio',`data-id="${word.id}"`)}<div class="writing-tools">${button('Escuchar más lento','slow','',`data-id="${word.id}"`)}</div><div class="question-options">${session.options.map((q,i)=>`<button class="answer-option" data-lesson="answer" data-id="${q.id}" aria-label="Opción ${i+1}: ${q.es}">${A.image(q,'','')}<small>OPCIÓN ${i+1}</small></button>`).join('')}</div><div id="answer-feedback" aria-live="polite"></div></div>`;foot=footer('Continuar','next',true);
  }else{
   body=`<div class="lesson-body"><span class="section-eyebrow">${part.type==='letters'?'ARMA LA PALABRA':'UN PASITO CON LAS LETRAS'}</span><h2 id="lesson-title">${part.type==='letters'?'Vamos letra por letra.':'¿Cómo se escribe?'}</h2><p class="lesson-sub">${part.type==='letters'?'Toca las letras en orden. Usa una pista si la necesitas.':'Puedes escribir, usar letras o mirar una pista.'}</p>${A.image(word,'write-art',word.es)}${audioButtons(word)}<p id="hint-answer" class="hint-answer" hidden lang="en"></p><div id="writing-area">${part.type==='letters'?lettersMarkup():`<form id="writing-form"><label for="word-input" class="sr-only">Escribe la palabra en inglés</label><input id="word-input" class="writing-input" type="text" inputmode="text" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" maxlength="32" aria-describedby="answer-feedback" placeholder="Tu palabra…"></form>`}</div><div class="writing-tools">${button('Ver una pista','hint','')}${part.type==='write'?button('Prefiero tocar letras','use-letters',''):button('Borrar una letra','undo','')}${button('Hoy solo quiero escuchar','skip-writing','')}</div><div id="answer-feedback" aria-live="polite"></div></div>`;foot=footer('Comprobar','check');
  }
  root().innerHTML=top()+body+foot;
  if(part.type==='learn'||part.type==='listen')A.Audio.play(word.id);
 }
 function lettersMarkup(){return`<div class="letter-answer" aria-label="Palabra que estás formando">${[...w().en].map((_,i)=>`<span class="letter-slot">${picked[i]!==undefined?A.esc(bank[picked[i]].letter):''}</span>`).join('')}</div><div class="letter-bank">${bank.map((b,i)=>`<button class="letter-tile" data-lesson="letter" data-index="${i}" ${picked.includes(i)?'disabled':''} aria-label="Letra ${b.letter}">${A.esc(b.letter)}</button>`).join('')}</div>`;}
 function record(correct){answerLog.push({id:w().id,correct,assisted});}
 function feedback(correct){
  answered=true;record(correct);const word=w();$('#answer-feedback').innerHTML=`<div class="feedback ${correct&&!assisted?'':'gentle'}">${correct?assisted?'¡Lo armamos juntos! Cada pista también ayuda.':'¡Sí! Lo descubriste.':'Vamos a aprenderla juntos.'} <strong lang="en">${word.en}</strong>${A.profile().settings.translation?' · '+word.es:''}<br>${correct?'Puedes escucharla una vez más antes de seguir.':'Esta es la respuesta. La volveremos a practicar otro día.'}</div>`;
  root().querySelectorAll('.answer-option,.letter-tile,.writing-tools button').forEach(b=>b.disabled=true);const input=$('#word-input');if(input)input.disabled=true;
  const next=root().querySelector('.lesson-footer .primary-btn');next.dataset.lesson='next';next.disabled=false;next.innerHTML='Continuar '+A.icon('arrow');if(correct)A.Audio.chime();else A.Audio.play(word.id);
 }
 function answer(id){if(answered)return;const correct=id===w().id;root().querySelectorAll('.answer-option').forEach(b=>{if(b.dataset.id===w().id){b.classList.add('correct');b.insertAdjacentHTML('beforeend','<span class="answer-check">✓</span>');}else if(b.dataset.id===id)b.classList.add('incorrect');});feedback(correct);}
 function checkWriting(){if(answered)return;const text=$('#word-input')?.value??picked.map(i=>bank[i].letter).join('');if(!text.trim()){A.toast('Prueba una letra o toca «Ver una pista».');return;}const correct=A.C.normalize(text)===A.C.normalize(w().en);if(!correct){$('#hint-answer').hidden=false;$('#hint-answer').textContent=w().en;}feedback(correct);}
 function hint(){if(answered)return;assisted=true;revealed=true;$('#hint-answer').hidden=false;$('#hint-answer').textContent=w().en;A.Audio.play(w().id);}
 function next(){if(current().type!=='learn'&&!answered)return;if(step+1<session.steps.length){step++;draw();}else finish();}
 function finish(){
  A.Audio.stop();const p=A.profile(),today=A.C.day();
  for(const id of exposed){const item=p.words[id]||{seen:0,attempts:0,correct:0,stage:0,due:today,last:'',stageDay:''};item.seen++;p.words[id]=item;}
  // Aggregate a word's activities before scheduling: a hinted or incorrect
  // spelling must not be hidden by an earlier correct listening response.
  const grouped=new Map();for(const a of answerLog){const prev=grouped.get(a.id)||{correct:true,assisted:false};prev.correct=prev.correct&&a.correct;prev.assisted=prev.assisted||a.assisted;grouped.set(a.id,prev);}
  for(const [id,value]of grouped)A.C.record(p,id,{...value,today});
  const correct=answerLog.filter(a=>a.correct&&!a.assisted).length,ids=[...grouped.keys()];
  const earned=A.C.complete(p,{id:session.id,mode:session.mode,words:ids,attempts:answerLog.length,correct,assisted:answerLog.filter(a=>a.assisted).length},today);
  if(session.mode==='weekly')p.weekly.push({date:today,correct,total:answerLog.length});p.weekly=p.weekly.slice(-52);
  const unlocked=A.unlock();A.save();A.render();
  const weekly=['weekly','practice'].includes(session.mode),needs=answerLog.filter(a=>!a.correct||a.assisted);root().innerHTML=`<div class="lesson-top">${button(A.icon('close'),'done','icon-btn','aria-label="Cerrar resultado"')}<div class="lesson-progress"><i style="width:100%"></i></div><span class="lesson-counter">¡COMPLETADO!</span></div><section class="result-body"><img class="result-art" src="assets/${weekly?'rainbow':'star'}.png" alt="" width="256" height="256"><span class="section-eyebrow" style="justify-content:center">OTRO PEQUEÑO GRAN DESCUBRIMIENTO</span><h2 id="lesson-title">${weekly?'¡Misión cumplida!':'¡Mira todo lo que descubriste!'}</h2><p>${weekly?'Este reto muestra lo que recordaste hoy. Seguiremos practicando juntos.':'Cada palabra es una nueva forma de ver el mundo. Lo estás haciendo muy bien.'}</p><div class="result-stats"><div><b>+${earned}</b><small>ESTRELLAS</small></div><div><b>${ids.length}</b><small>PALABRAS PRACTICADAS</small></div>${weekly?`<div><b>${correct}/${answerLog.length}</b><small>SIN PISTAS</small></div>`:''}</div><div class="result-words">${session.words.map(q=>A.image(q,'',q.en)).join('')}</div>${unlocked.length?`<div class="feedback">✦ Nueva insignia: ${unlocked.map(d=>d.title).join(', ')}</div>`:''}<p>${needs.length?'Algunas palabras volverán antes en tus repasos. Aprender necesita varios encuentros.':'Vuelve otro día para recordar estas palabras. Así crece tu memoria.'}</p>${earned===0?'<p class="form-help">Ya habías ganado estrellas por estas palabras hoy. Repetir sigue ayudando a aprender.</p>':''}<div class="modal-actions">${button('Ver mi álbum','album','soft-btn')}${button('Volver a mi aventura','done')}</div><p class="form-help">${!A.storageAvailable()?'No se pudo guardar en este navegador. Exporta un respaldo desde el espacio de adultos.':session.mode==='weekly'?'Reto semanal guardado. El siguiente registro se habilita en 7 días.':session.mode==='practice'?'Práctica libre: no se añade otro examen semanal.':'Progreso guardado en este dispositivo.'}</p></section>`;
  session.finished=true;A.Audio.instruction('done');
 }
 function requestExit(){if(!session||session.finished||traceWord){close();return;}if(exitPending)return;resumeMarkup=root().innerHTML;resumeInput=$('#word-input')?.value||'';exitPending=true;A.Audio.stop();root().innerHTML=`<section class="lesson-exit"><span class="section-eyebrow" style="justify-content:center">TÚ DECIDES EL RITMO</span><h2 id="lesson-title">¿Hacemos una pausa?</h2><p>Tu progreso anterior está a salvo.<br>Esta aventura se guarda al completarla.</p><div>${button('Seguir con mi aventura','resume')}${button('Volver al inicio','discard','outline-btn')}</div></section>`;}
 function close(){A.Audio.stop();dialog().close();session=null;traceWord=null;exitPending=false;A.render();}
 function trace(word){traceWord=word;session=null;dialog().showModal();root().innerHTML=`<div class="lesson-top">${button(A.icon('close'),'done','icon-btn','aria-label="Cerrar trazado"')}<span class="section-eyebrow">EXPLORAR CON LAS MANOS</span></div><section class="lesson-body"><h2 id="lesson-title">Dibuja tu palabra.</h2><p class="lesson-sub">Sigue las letras con tu dedo, lápiz digital o ratón. No se califica.</p>${A.image(word,'write-art',word.es)}<div class="audio-actions">${button(A.icon('sound')+' Escuchar','audio','',`data-id="${word.id}"`)}</div><div class="trace-wrap"><span class="trace-guide" lang="en">${word.en}</span><canvas id="trace-canvas" aria-label="Área libre para trazar ${word.en}"></canvas></div><div class="writing-tools">${button('Borrar y volver a probar','clear-trace','')}</div><p class="notice">Si escribir hoy cuesta, escuchar y señalar también cuentan.</p></section><footer class="lesson-footer">${button('Listo, volver a descubrir','done')}</footer>`;prepareCanvas();A.Audio.instruction('trace');}
 let traceCanvas,traceContext,traceObserver,drawing=false,lastPoint;
 function prepareCanvas(){traceObserver?.disconnect();traceCanvas=$('#trace-canvas');traceContext=traceCanvas.getContext('2d');const resize=()=>{const rect=traceCanvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);traceCanvas.width=rect.width*dpr;traceCanvas.height=rect.height*dpr;traceContext.setTransform(dpr,0,0,dpr,0,0);traceContext.lineWidth=6;traceContext.strokeStyle='#756add';traceContext.lineCap='round';traceContext.lineJoin='round';};traceObserver=new ResizeObserver(resize);traceObserver.observe(traceCanvas);resize();const point=e=>{const r=traceCanvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};};traceCanvas.addEventListener('pointerdown',e=>{drawing=true;lastPoint=point(e);traceCanvas.setPointerCapture(e.pointerId);e.preventDefault();});traceCanvas.addEventListener('pointermove',e=>{if(!drawing)return;const to=point(e);traceContext.beginPath();traceContext.moveTo(lastPoint.x,lastPoint.y);traceContext.lineTo(to.x,to.y);traceContext.stroke();lastPoint=to;});for(const evt of ['pointerup','pointercancel','lostpointercapture'])traceCanvas.addEventListener(evt,()=>drawing=false);}
 function act(action,b){
  if(action==='audio')A.Audio.play(b.dataset.id);if(action==='slow')A.Audio.play(b.dataset.id,true);
  if(action==='instruction')A.Audio.instruction(current()?.type||'learn');if(action==='exit')requestExit();
  if(action==='done'||action==='discard')close();if(action==='album'){close();A.navigate('album');}
  if(action==='resume'){exitPending=false;root().innerHTML=resumeMarkup;if($('#word-input'))$('#word-input').value=resumeInput;}if(action==='next')next();if(action==='answer')answer(b.dataset.id);if(action==='check')checkWriting();if(action==='hint')hint();
  if(action==='letter'&&!answered){const index=Number(b.dataset.index);if(picked.length>=w().en.length||picked.includes(index))return;picked.push(index);$('#writing-area').innerHTML=lettersMarkup();}
  if(action==='undo'&&!answered){picked.pop();$('#writing-area').innerHTML=lettersMarkup();}
  if(action==='use-letters'&&!answered){assisted=true;current().type='letters';picked=[];$('#writing-area').innerHTML=lettersMarkup();b.dataset.lesson='undo';b.textContent='Borrar una letra';}
  if(action==='skip-writing'&&!answered){session.steps.splice(step,1);if(step<session.steps.length)draw();else finish();}
  if(action==='clear-trace')traceContext.clearRect(0,0,traceCanvas.width,traceCanvas.height);
 }
 return{init,start,trace};
})();
